/* 隐藏首页文章列表小标题 */
.post-list-heading {
    display: none !important;
}

/* 隐藏页脚 footer 大标题（站点名） */
.footer-heading {
    display: none !important;
}

/* 隐藏 RSS 订阅 */
.feed-subscribe, .feed-subscribe * {
    display: none !important;
    visibility: hidden !important;
    height: 0 !important;
    margin: 0 !important;
    padding: 0 !important;
}
