baseURL = "https://doctor-wind.github.io/larkchan.github.io/"
languageCode = "zh-cn"
title = "蚂蚁的花园"
theme = "PaperMod"
paginate = 10

[params]
  defaultTheme = "light"
  disableThemeToggle = true
  DateFormat = "2006-01-02"
  ShowReadingTime = false
  ShowShareButtons = false
  ShowCodeCopyButtons = true
  mainSections = ["daily","posts"]

  [params.homeInfoParams]
    Title = "Daily"
    Content = "蚁路碎语"

[menu]
  [[menu.main]]
    name = "每周采蜜"
    url = "/archives/"
    weight = 10

[outputs]
  home = ["HTML","RSS","JSON"]

# 按日期的固定链接（可改）
[permalinks]
  posts = "/:year/:month/:day/:slug/"
  daily = "/:year/:month/:day/:slug/"
