baseURL = "https://larkchan.github.io/"
languageCode = "zh-cn"
title = "Lark 的博客"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  defaultTheme = "light"
  disableThemeToggle = true
  DateFormat = "2006-01-02"
  ShowReadingTime = false
  ShowShareButtons = false
  ShowCodeCopyButtons = true
  mainSections = ["daily","posts"]

[menu]
  [[menu.main]]
    name = "归档"
    url = "/archives/"
    weight = 10

[outputs]
  home = ["HTML","RSS","JSON"]

[permalinks]
  posts = "/:year/:month/:day/:slug/"
  daily = "/:year/:month/:day/:slug/"
